### ISSUE TITLE
переработка лендинга

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#102]
- [x] составить план блоков лендинга (как это работает-схема? для кого сервис? видео? итп)
- [x] найти референсы
- [x] реализовать

**Comment by danilstoyanov** [comment]
http://www.fantasyleague.com/Pro/
Нужна пошаговая инструкция как тут
![image](https://user-images.githubusercontent.com/18240896/56355368-c8bd6480-61de-11e9-80ae-ca998e225ae6.png)

**Comment by danilstoyanov** [comment]
Нужен блок для стримеров

**Comment by danilstoyanov** [comment]
Подвал добавить на главную также, со ссылочками

**Comment by danilstoyanov** [comment]
Блок с популярными турнирами по LoL (Участвуй в фентези турнирах на основе крупных ивентов по LoL и логотипчики всякие крупных турниров с названиями)

**Comment by danilstoyanov** [comment]
Call-to-action блок также нужен. Не только на главной секции там где кнопка войти через Google

**Comment by danilstoyanov** [comment]
![main](https://user-images.githubusercontent.com/18240896/56502212-40123180-651a-11e9-99be-d5d1206818f4.jpg)
Начал работу над дезигном
