### ISSUE TITLE
История операций удаленные турниры

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#109]
Главная страница > кнопка баланса > операции
Смотрю историю списания/получения средств турнира, который есть в списке - все ок.
Но если выбрать турнир, который был удален, будет бесконечная загрузка страницы.
Предложение - сделать какое либо окошко, либо запретить кликать на удаленные турниры в истории.

**Comment by kot91ivan** [comment]
Этой страницы у нас больше нет, может закроем?

**Comment by danilstoyanov** [comment]
Да, пожалуй закроем
