### ISSUE TITLE
публичный профиль пользователя

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#11]
публичный профиль
КАК МЫ ПОПАДАЕМ В ПУБЛИЧНЫЙ ПРОФИЛЬ: сама поделится ссылкой, клик по списку из общего рейтинга, в турнире рейтинг кликабелен
-- никнейм
-- аватарка
-- о себе
-- 5 последних турниров в которых принималось участие (НЕ КЛИКАБЕЛЬНЫ!)
--- название турнира
--- число участников
--- цена входа
--- занятое место в рейтинге 
-- общий рейтинг
--- общее число турниров в которых принято участие
--- количество заработанных денег
--- место в общем рейтинге

**Comment by danilstoyanov** [comment]
Роман, нам нужен БЭК для реализации данной задачи
