### ISSUE TITLE
Ревью стримерских турниров

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#115]
- [x] Когда заходишь в профиль под стримером, не понятно, стример ты или нет, нужно как нибудь помечать

- [x] Уведомление о том, что нужно добавить summoner name в настройках

- [x] В выборе игрока цифры - вниз

- [x] В выборе игрока поиск по игрокам

- [x] Положение кнопки редактировать игроков

- [x] Не открывается сайдбар с нотификациями

- [x] Баг с обновловлением результатов матчей сразу же после перехода на созданный турнир

- [x] Починить лайвапдейты

- [x] Нотификация о турнире - ссылка!

- [x] Через лол Апи сделать проверку, что такой summoner name существует

- [x] Баги с аватарками

- [x] Баг с анимацией нотификации при закрытии через клик на Х

**Comment by danilstoyanov** [comment]
![image](https://user-images.githubusercontent.com/18240896/57681664-ceb93080-7638-11e9-9292-fcb6896db7e8.png)
Это к багу со скроллбарами. Их два. А должен быть один, только у компонента с выбором игроков

**Comment by danilstoyanov** [comment]
![image](https://user-images.githubusercontent.com/18240896/57681870-412a1080-7639-11e9-8c20-77b26bfb5b25.png)
Положение кнопки сместить влево

**Comment by danilstoyanov** [comment]
![image](https://user-images.githubusercontent.com/18240896/57681973-76366300-7639-11e9-80cb-cc6b542ad52e.png)
При клике на кнопку добавить турнир, проверяем, выставил ли юзер свой summoner name. Это поле находится в настройках. Если не выставил, то сделать нотификацию о том что это следует сделать. Нотификация - ссылка на настройки.
![image](https://user-images.githubusercontent.com/18240896/57682048-9d8d3000-7639-11e9-8adc-aa05517fdb54.png)

**Comment by danilstoyanov** [comment]
![image](https://user-images.githubusercontent.com/18240896/57725773-90525e80-7696-11e9-8705-fcec82a8ad4e.png)
Нужно пофиксить отступы и скроллбар
