### ISSUE TITLE
баланс

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#12]
- [x] сверху справа появляется сумма в долларах при клике, выпадашка с тремя пунктами (история операций, ввести деньги и вывести деньги)
- [x] (бекенд) счетчик баланса у юзера и отдельная модель история операций
- [x] страница история операций (список: дата, сумма)
- [x] кнопка вывести деньги - отнимает 10 долларов и кнопка ввести деньги прибавляет 10 долларов (соотв. бекенд добавляет запись в историю операций итп)

**Comment by danilstoyanov** [comment]
Иван привет!
Я подготовил болванку страницы истории транзакций (http://localhost:3000/transactions)
Тебе необходимо получить данные со списком историй транзакций, и вывести на экран. Предлагаю использовать грид компонент (например как в рейтнгах).

Для получения истории тразакций нужно использоать TransactionsService, метод getTransactionsHistory. Он вернёт список транзакций проведенных юзером. Сигнатура ответа следующая:
![trans](https://user-images.githubusercontent.com/18240896/52970432-c8624200-33c4-11e9-9338-86b4289399cd.PNG)

Думаю, на экран нужно вывести сумму, дату, тип операции (приход, расход), источник операции (юзер может положить деньги, или потратить деньги на участие в турнире, или получить выигрыш от турнира)
