### ISSUE TITLE
интеграция платежной системы

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#120]
- [x] убираем баланс
- [x] убираем страницу история транзакций
- [x] добавляем страницу "трафеи" (на этой странице карточки с наградами, каждая карточка имеет картинку, заголовок (название) и описание (ключ)
- [ ] при принятии участия в турнире (или при его создании) отправляем на страницу с оплатой
- [ ] при создании турнира указываем сумму выигрыша, а также количество участников (сумма участия это - 80% от выигрыша деленная на количество участников)
- [ ] появляется параметр - количество слотов в фентези турнире. Пока не наберется МИНИМУМ от этого количества, турнир нельзя финализировать. (в процессе)

**Comment by kot91ivan** [comment]
Страница Trophies создана.
Компонент карточек для трофеев создан.
