### ISSUE TITLE
Видно не больше 9 человек

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#121]
Участвовали 20+ , а видно 9
![image](https://user-images.githubusercontent.com/46968947/58026808-fbc97f80-7b1f-11e9-9497-b5f4cebe345b.png)

**Comment by kot91ivan** [comment]
Исправил и слил изменения в ветку Dev

**Comment by kot91ivan** [comment]
Добавлен цвет текущего чемпиона в Leaderboard

**Comment by kot91ivan** [comment]
Тогда имеет смысле ли сделать кнопку чтобы раскрывать список всех участвующих, когда их очень много.
