### ISSUE TITLE
Скролл при добавлении игроков

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#127]
Скролл криво работает, неудобно
![image](https://user-images.githubusercontent.com/46968947/58711953-440e5a80-83c8-11e9-8a1d-18afefe36348.png)
![image](https://user-images.githubusercontent.com/46968947/58711997-54bed080-83c8-11e9-9453-ad0d1b6bb558.png)

**Comment by kot91ivan** [comment]
Изменения отправлены в dev
