### ISSUE TITLE
Статистика игроков

### ISSUE THREAD

**Issue by danilstoyanov** [uz0/pick.gg#136]
- [x] Турнир с Максоном в субботу показал, что людям интересно сколько баллов какой игрок заработал очков. Предлагаю для удобства в таблицу результатов добавить поле score или total а также отсортировать игроков в зависимости от результатов.
![Статистика](https://user-images.githubusercontent.com/18240896/58785962-47cff600-85ef-11e9-8fa6-aaf55d20a48c.PNG)

**Comment by kot91ivan** [comment]
Total добавил в ветку Dev, вопрос сортировка тогда получается по общему количеству очков?

**Comment by danilstoyanov** [comment]
> Total добавил в ветку Dev, вопрос сортировка тогда получается по общему количеству очков?
Да, можно по баллам сортировать ,пока вешаю лейбл для тестирования того что ты уже запилил
