### ISSUE TITLE
Починить и тщательно протестировать кнопку "Начать турнир"

### ISSUE THREAD

**Issue by danilstoyanov** [uz0/pick.gg#142]
Необходимо провести доработку и тестирование этой кнопки.
Доработка:
- [ ] Убедиться что её видно только стримеру-создателю турнира.
- [ ] Убедиться, что её можно нажать только один раз. 
- [ ] Убедиться, что показывается сообщение о том, что турнир начался
Тестирование:
- [ ] Убедиться что её видно только стримеру-создателю турнира.
- [ ] Убедиться, что её можно нажать только один раз. 
- [ ] Убедиться, что показывается сообщение о том, что турнир начался
![image](https://user-images.githubusercontent.com/18240896/58786683-cc6f4400-85f0-11e9-8341-80ca3aac258d.png)

**Comment by kot91ivan** [comment]
![image](https://user-images.githubusercontent.com/25117131/58884292-c2c90780-86e8-11e9-8e3d-64b2d24c1877.png)
Может имеет смысл кнопки перенести в другое место?
