### ISSUE TITLE
Настроить обязательный прогон ESlint'а на push.

### ISSUE THREAD

**Issue by Ermakoy** [uz0/pick.gg#147]
Предлагаю настроить prepush хук.
Есть возможность настроить разные конфиги для фронта и бека.  Думаю, что это позволит не тратить силы на проверку стилистических вещей в коде и сосредоточиться на бизнес логике.

Так же есть такие интересные конфиги, предлагаю принять их во внимание:
- [unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn)
- [AirBnB](https://github.com/airbnb/javascript)
- [Standard](https://standardjs.com)

Напишите, что думаете.

**Comment by dcversus** [comment]
AirBnB мне нравится (как и стандарт в целом)... а про уникорн впервые вообще вижу и слышу

**Comment by efim1382** [comment]
ну я глянул,, AirBnB да, кайфовая вещь, разве что за исключением пары моментов

**Comment by danilstoyanov** [comment]
Посмотрел 3 конфига.
Я бы их так расположил
1) Standard
2) AirBnB
3) Unicorn

Хотя, AirBnB включает в себя 70% Standard конфига. Так что можно юзать AirBnB

**Comment by dcversus** [comment]
чекнула правила https://github.com/sindresorhus/eslint-plugin-unicorn, мне понравилось, ничего не вызвало недоумения итп. я бы придерживалась его
