### ISSUE TITLE
Правка файловой структуры проекта

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#157]
хочется чтобы структура была такая
```
- client
- - package.json
- server
- - package.json
- common
package.json
```

при этом в корневом просто снипеты для удобного запуска. Что стоит подумать?
- где держим правила еслинта (отдельно в каждом проекте?)
- инфра для юнит тестов (отдельно в каждом проекте?)
итп

**Comment by Ermakoy** [comment]
Правила eslint'а будут лежать в корне каждого проекта т.е.
```
- client
  - .eslintrc
- server
  - .eslintrc
```
А скрипт в корневом package.json будет эти проверки запускать. Так же будет возможность запуска из каждого пакета

Инфра для тестов тоже отдельно т.к. нужны разные среды
