### ISSUE TITLE
Линтер

### ISSUE THREAD

**Issue by efim1382** [uz0/pick.gg#160]
![image](https://user-images.githubusercontent.com/13278088/59427441-51254380-8de3-11e9-9389-ddb57cf2dbd0.png)
линтер сам переименовывает сокращенные названия переменных/полей в полные. И, например, если я передаю в configureStore поле devTools
```
const store = configureStore({
  reducer: rootReducer,
  middleware: [thunk, logger],
  devTools: true,
});
```
то линтер ругается, что поле сокращенное и хочет переименовать в developersTools

**Comment by Ermakoy** [comment]
@efim1382 Если будет ещё что-то подобное, то референси строчки прямо на гитхабе, чтобы можно было сразу посмотреть файлы
