### ISSUE TITLE
Рефакторинг названий CSS классов

### ISSUE THREAD

**Issue by danilstoyanov** [uz0/pick.gg#18]
Благодаря mad skills Романа, у нас в проекте появились CSS модули.
Главная фича, которую дают нам CSS модули - это инкапсуляция стилей в рамках одного компонента с целью избегания негативных эффектов глобального CSS.

Мы хотим избежать лишних переопределений стилей в коде.
(Советую прочесть https://habr.com/ru/company/mailru/blog/319956/ чтобы лучше понять историю развития подходов работы с CSS и понять что модули делают под капотом)

Сейчас в проекте у нас встречаются такие стили:
![image](https://user-images.githubusercontent.com/18240896/51999518-00641c80-24cc-11e9-9a8d-44194d3d77dd.png)

Это стили для компонента newTournament. В данном случае, нам необязательно начинать каждое css правило с newTournament, т.к. наши стили будут изолированы от глобальной области видимости в компоненте newTournament.

По аналогии, желательно везде избавиться от подобных определений.

Также. В рамках данного проекта, согласно контракту который мы все разработали, для именования стилей мы используем не Camel Case а дефис - или _
пример:
https://github.com/dcversus/uni-chat/blob/master/src/components/dropdown/style.css

**Comment by kot91ivan** [comment]
Спасибо за подробное описание) ♥
