### ISSUE TITLE
Интерфейсные тесты

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#189]
- [x] Составить список актуальных сценариев пользователя
- [ ] Определить приоритеты сценариев
- [ ] Реализация автоматизации сценариев

**Comment by dcversus** [comment]
https://github.com/uz0/pick.gg/wiki/%D0%A1%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F

**Comment by Hoffasha** [comment]
**РЕГИСТРАЦИЯ ПОЛЬЗОВАТЕЛЕЙ В ПРИЛОЖЕНИИ**
- [x] Пользователь переходит на главную страницу /home 
- [x] Пользователь нажимает на кнопку Start with Google 
- [x] Пользователь заполняет данные в форме Google 
- [x] В случае успешного заполнения, мы проверяем на бэкенде, есть ли в базе юзер с таким email, если нет, то создаём нового юзера 
- [ ] Происходит редирект юзера на страницу /settings 
- [ ] Там подсвечивается поле summonerName и показывается панелька, что его необходимо заполнить 
- [ ] Также, игроку необходимо выбрать свой регион, в котором он играет в LOL 
- [ ] После заполнения своего summonerName, юзер может пройти все оставшиеся сценарии 

**ОБНОВЛЕНИЕ ИНФОРМАЦИИ О СЕБЕ**
- [ ] При переходе на страницу настройки /settings юзер должен увидеть форму доступуню для редактирования
- [ ] В форме редактирования юзер может менять: 
summonerName (уникальное) 
- [ ] imageUrl (аватарка) 
- [ ] about (текст о себе) 
- [ ] twitchAccount (ссылка на твич аккаунт) 
- [ ] regionId (селект с выбором региона игры)
- [ ] prefferedPosition (селект с предпочитаемой ролью в игре) 

**ПРЕДОСТАВЛЕНИЕ ДАННЫХ О НАЛИЧИИ КАНАЛА НА TWITCH, ВЕРИФИКАЦИЯ И ВОЗМОЖНОСТЬ ПРОВОДИТЬ ТУРНИРЫ**
- [x] У каждого юзера есть потенциальная возможность создавать турниры +++
- [x] Для этого необходимо получить статус стримера +++
- [x] Юзер переходит в свои настройки, и выбирает twitch account +++
- [ ] Юзер связывается с администраицей (или администрации приходит заявка об изменении значения поля twitchAccount). -----
- [x] Администратор проверяет канал указанный юзером, верифицирует его +++
- [x] После верификации, пользователь получает галочку на аватарке и возможность создавать турниры +++

**ПОЛУЧЕНИЕ РЕВАРДОВ ДЛЯ НАГРАЖДЕНИЯ УЧАСТНИКОВ ТУРНИРА**
- [x] Ревард - это карточка, обладающая уникальным кодом, который можно использовать в LOL чтобы залутать что-нибудь полезное 
- [x] Для получения ревардов, стример должен обратиться к администраторам сервиса 
- [x] Администратор создаёт награды и "переводит" их на имя стримера 
- [x] Стример заходит в инвентарь, и там может видеть список наград, которыми он обладает на данный момент 
- [x] Стример использует реварды по своему усмотрению 

**!!!Создание и проведение турнира пока не работают!!!**
