### ISSUE TITLE
Мобильная версия

### ISSUE THREAD

**Issue by danilstoyanov** [uz0/pick.gg#19]
- [x] Лендинг (стартовая страница)
- [x] Страница логина
- [x] Страница регистрации
- [x] Страница турниров (мы туда попадаем после логина)
- [x] Страница с карточками команды, выбранной на турнир
- [x] Страница публичный профайл
- [x] Страница настройки профайла
- [x] Страница рейтинг пользователей

**Comment by danilstoyanov** [comment]
- [ ] Лендинг (стартовая страница)

- [ ] Страница логина

- [ ] Страница регистрации

- [ ] Страница турниров (мы туда попадаем после логина)

- [ ] Страница с карточками команды, выбранной на турнир

**Comment by kot91ivan** [comment]
- [ ] Страница публичный профайл

- [ ] Страница настройки профайла
