### ISSUE TITLE
Подключить eslint плагин для автоматической сортировки импортов

### ISSUE THREAD

**Issue by Ermakoy** [uz0/pick.gg#191]
В последнее время много путаницы в PR'ах относительно импортов. Вот есть eslint [плагин](https://github.com/Tibfib/eslint-plugin-import-helpers)
Думаю, он может помочь нам побороть это уже на стадии коммитов, благо многие вещи он правит сам

**Comment by dcversus** [comment]
гуд, го зальем это к себе <3
