### ISSUE TITLE
Мета информация

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#201]
Хочу чтобы когда кто-то кидал ссылку на лендинг или конкретный турнир, соц сети имели расширенный снипет. Для этого нужно

- [ ] на главной добавить мета-информацию
- [ ] страницу конкретного турнира (а именно header с мета-информацией) отдавать через express приложение

![image](https://user-images.githubusercontent.com/8696354/61791420-96955180-ae22-11e9-9373-73e729816893.png)

**Comment by ovchingus** [comment]
Имеется в виду header который с http response приходит? Туда мета теги из html <head> как то не получается засунуть). 
![image](https://user-images.githubusercontent.com/31659505/66165839-4f0b1d00-e63e-11e9-9809-d6a2d7075f7d.png)

**Comment by ovchingus** [comment]
Насколько я понимаю, соцсети когда ссылку вставляешь, делают get запрос по ней, те на страницу турнира, те надо просто добавить мета теги для страницы уже html? или можно как то без ожидания пока реакт соберет страницу сделать?

**Comment by dcversus** [comment]
на express делаем переопределение роутов /tournaments/:id и подкладываем в index.html несколько мета-тегов для сниппета соц сетей

**Comment by SerenityLeslie** [comment]
Сейчас вот так. Думаю, с задачей справились.
![image](https://user-images.githubusercontent.com/54684278/68703146-ad5ae200-0592-11ea-9b89-6f256f7aa270.png)
