### ISSUE TITLE
Пропадают плашки Admin и Streamer

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#202]
После редактирования профиля пропадают теги стример админ, f5 помогает
так как до f5 пропадает админка (панель управленния)
то есть полностью руинит до перезагрузки
![image](https://user-images.githubusercontent.com/46968947/61885819-2e6c6b80-af07-11e9-8cf6-4e41ca7b9f93.png)

**Comment by danilstoyanov** [comment]
Баг исправлен ^^)
