### ISSUE TITLE
Флоу с авторизацией

### ISSUE THREAD

**Issue by danilstoyanov** [uz0/pick.gg#208]
Нам необходимо реализовать следующий флоу с авторизацией:

1) Пользователь, не зарегистрированный в системе, где-либо видит ссылку на турнир, и осуществляет переход по ней.

2) Пользователь переходит на страницу турнир и ему доступны те же действия, что и зарегистрированным пользователям (стать аппликантом, сделать прогноз).

3) Однако для того, чтобы стать аппликантом или сделать прогноз, при клике на кнопку мы должны проверять, авторизован ли пользователь, и если нет, то редиректить его на главную страницу с целью авторизации.

4) После того, как пользователь зарегистрировался, нам необходимо, чтобы он также свой **summonerName** ввёл, так как именно на этом поле (а не на username) у нас завязано большинство бизнес-логики. О том как это сделать, нужно крепко подумать.

**Comment by danilstoyanov** [comment]
![image](https://user-images.githubusercontent.com/18240896/61946006-23b6e280-afaa-11e9-8b34-1bc42fefd9b9.png)

**Comment by Ermakoy** [comment]
В общем, идея такая, что мы делаем функцию, типа drop-it регистрации. Она, как функция высшего порядка, принимает в себя коллбэк(действие, которое можно показать незарегестрированному). Потом, когда пользователь пытается это действие совершить, мы проверяем, вошёл ли он в систему, и, если нет, то открываем мочалку регистрации и после неё уже вызываем функцию, которую передали(изначальное действие), только теперь оно будет выполнено уже зарегистрированным пользователем

**Comment by danilstoyanov** [comment]
Круто! В итоге мы реализовали регистрацию по данному сценарию.
