### ISSUE TITLE
Навигация на мобильной версии приложения

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#212]
На моб версии очень нужна либо кнопка турниры, либо значок, так как кнопка Pick.gg ведет на авторизацию, а чтобы выйти из турнира, придется открывать меню и там кликать турниры, школьники точно не сообразят быстро
![image](https://user-images.githubusercontent.com/46968947/62382267-e0361880-b555-11e9-9e3d-8996f09a79a8.png)

![image](https://user-images.githubusercontent.com/46968947/62382281-ea581700-b555-11e9-8cab-19558fe6eca9.png)

**Comment by dcversus** [comment]
Нужно составить основные флоу приложения
