### ISSUE TITLE
основы тестирования

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#23]
- [ ] авторизоваться на сервисе через интерфейс, посмотреть во вкладке сеть запрос, повторить через postman
- [ ] зарегестрироваться через интерфейс, повторить через postman
![image](https://user-images.githubusercontent.com/8696354/52539858-f972bf00-2d93-11e9-97cb-ff68aef5ba0b.png)

**Comment by Hoffasha** [comment]
![1](https://user-images.githubusercontent.com/46968947/52575029-8f5b2800-2e2e-11e9-9252-a32c52fd4d51.jpg)
![2](https://user-images.githubusercontent.com/46968947/52575031-8f5b2800-2e2e-11e9-9aa1-738cbc91517f.jpg)

**Comment by Hoffasha** [comment]
![3](https://user-images.githubusercontent.com/46968947/52575116-b3b70480-2e2e-11e9-90e0-739de420a859.png)
