### ISSUE TITLE
Ошибка при создании реварда

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#230]
Нужно добавить окно с ошибкой, что нужно ввести ID пользователя.
Сейчас просто выкидывает на страницу ошибки.
![image](https://user-images.githubusercontent.com/46968947/63068687-c06eff00-bf1c-11e9-8289-62ae9b440123.png)

**Comment by danilstoyanov** [comment]
Пофиксил. Фикс в деве. Не забудь спулиться перед перевроверкой
