### ISSUE TITLE
Переход на следующую страницу после создания турнира

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#233]
Локально в деве после всех правил турнира сломался переход на следующую страницу, если заполнять правила не по порядку, переход происходит при последовательности: правила кда, матчи, награды.
При последовательности кда, награда, матч перехода нет.
Предлагаю сделать переход просто после последнего заполненного пункта
![image](https://user-images.githubusercontent.com/46968947/63134953-747f9100-bfd4-11e9-8f68-bd9030126ae0.png)

**Comment by danilstoyanov** [comment]
Исправлено, нужно перепроверить, пока что в dev
