### ISSUE TITLE
Настройки турнира: нельзя добавить более одного реварда

### ISSUE THREAD

**Issue by SerenityLeslie** [uz0/pick.gg#245]
http://pick.gg/tournaments/5d714e538a6b280017a78ae9

![image](https://user-images.githubusercontent.com/54684278/64801876-140f4f80-d592-11e9-94d7-bfd6e67935d8.png)

Отсутствует кнопка добавления более чем одного реварда. Есть только возможность эдитить уже созданный ревард. Так же его нельзя удалить.

**Comment by SerenityLeslie** [comment]
Ничего не изменилось. Можно только эдитить один старый ревард. Нельзя ни удалить, ни добавить новый 
![image](https://user-images.githubusercontent.com/54684278/68700425-91087680-058d-11ea-8a84-114c79b5467b.png)

**Comment by ovchingus** [comment]
Короче, как сейчас работает: нажимаешь на карандашик, открывается модалка, где написано edit tournament rewards, это окно чисто для удаления или редактирования существующих, при клике submit подтвердятся текущие изменения в текущем "режиме" редактирования. Если нажать на add, откроется по сути другое окно, уже для добавления новых наград, в нем список доступных пользователю наград, он их может выбрать и настроить и нажать submit чтоб пождтвердить, тогда модалка тоже закроется.

 Видимо короче это не очень юзер френдли получилось, можно было бы сделать так:
- Сделать все в одном окошке, и добавление и редактирование, но тогда нужно два списка показывать: доступных к добавлению и уже добавленных наград, непонятно как это должно выглядеть.
- Также по клику на карандаш открывается редактирование, в нем есть кнопочка add, можно ее нажать и появится выбор наград на добавление, когда выбирает пользователь награды и нажимает submit, его перекидывает на edit, где он уже видит новые добавленные награды

**Comment by dcversus** [comment]
Модальное окно редактирования наград - меняешь конфигурацию (добаляешь / редактируешь) и жмякаешь сабмит, на сервер отправляем ПОЛНЫЙ набор наград к турниру, как patch к нему. Применяем сразу все.

Без каких либо ожиданий, дополнительных походов на бек при add итп.

@ovchingus сделаешь?
