### ISSUE TITLE
Edit tournament rewards: дропдаун дублирует выбранное в обоих меню

### ISSUE THREAD

**Issue by SerenityLeslie** [uz0/pick.gg#246]
![image](https://user-images.githubusercontent.com/54684278/64801943-3f923a00-d592-11e9-993c-47ef4ec5087d.png)

**Шаги:** 
1. Зайти под админом на турнир http://pick.gg/tournaments/5d714e538a6b280017a78ae9 (а вообще на любой) 
2. Нажать на иконку карандаша edit rewards
3. В появившемся попапе в дропдауне place выбрать какое-то место(к примеру, second) 

**Результат:** контент продублируется в дропдауне 2 раза, так не должно быть. 
То же самое произойдет и в поле role

**Comment by danilstoyanov** [comment]
Чтобы исправить данный баг, нужно отслеживать состояние компонента, и фильтровать уже выбранные реварды, чтобы избежать дублирования наград.

**Comment by SerenityLeslie** [comment]
Не выглядит пофикшенным
![image](https://user-images.githubusercontent.com/54684278/68700294-58689d00-058d-11ea-8c64-a89cd6f2af7f.png)

**Comment by SerenityLeslie** [comment]
Пофикшено и потещено
