### ISSUE TITLE
Список Summoners: пустой таб без никнейма

### ISSUE THREAD

**Issue by SerenityLeslie** [uz0/pick.gg#248]
Принимая человека в Summoners из списка Applicants, под summoners добавляется пустое поле, без никнейма. При этом под applicants остается пустое поле со статусом accepted. Изменить логику следующим образом: 

- принимая человека на турнир, его никнейм долен отображаться под summoners БЕЗ СТАТУСА 
- принимая человека на турнир, он пропадает из списка applicants ВООБЩЕ 
![image](https://user-images.githubusercontent.com/54684278/64802936-6ea9ab00-d594-11e9-9e4b-5a4d8cf3b64f.png)

**Comment by danilstoyanov** [comment]
На заметку тому, кто будет фиксить данный баг.

Такое поведение можно получить, если applicant будет иметь пустое поле summonerName.

Для того чтобы это исправить, при подачи аппликантом заявки, нам нужно выполнять проверку, заполнено ли поле summonerName, и если оно пустое (' ' || null), тогда показываем модалку, в которой просим заполнить summonerName.

Далее, модалка делает запрос на обновление summonerName, и в случае успешного обновления, делаем второй запрос чтобы стать applicant.

**Comment by SerenityLeslie** [comment]
![image](https://user-images.githubusercontent.com/54684278/66591162-005c0680-eb9b-11e9-8b52-a2391521c017.png)
![image](https://user-images.githubusercontent.com/54684278/66591182-094cd800-eb9b-11e9-9966-dfe7b9ba9e39.png)
Как я вижу, ничего не изменилось

**Comment by dcversus** [comment]
@SerenityLeslie а дай ссылки где и под каким юзером смотришь пж))

**Comment by SerenityLeslie** [comment]
http://pick.gg/tournaments/5d9f665baa31620017493516 юзер админ Leslie_the_Soldier 
и юзер-аппликант Jana Jana - pickgg.test@gmail.com
![image](https://user-images.githubusercontent.com/54684278/66591631-056d8580-eb9c-11e9-8278-52b74b99670f.png)
