### ISSUE TITLE
Edit summoners: при нажатии на edit над summoners открывается пустая страница

### ISSUE THREAD

**Issue by SerenityLeslie** [uz0/pick.gg#249]
Шаги: 
- Зайти на http://pick.gg/tournaments/5d714e538a6b280017a78ae9 
- Кликнуть на edit рядом с summoners 

Результат: от клика на edit открылась белая страница

**Comment by dcversus** [comment]
не можем воспроизвести

**Comment by SerenityLeslie** [comment]
Как воспроизвести: 
- Создать турик
- добавить туда ревардов
- добавить каких-либо summoners
- после этого, кликнуть на кнопку edit 
- у меня до сих пор совершается переход на белую страницу после клика эдит

![image](https://user-images.githubusercontent.com/54684278/68698856-826c9000-058a-11ea-9886-a1392f2d78b2.png)

Гифка с багом:
![AwesomeScreenshot-2019-11-12-1573583300509](https://user-images.githubusercontent.com/54684278/68699227-4a198180-058b-11ea-9084-ad50e930f1a7.gif)

**Comment by SerenityLeslie** [comment]
Пофиксилось
