### ISSUE TITLE
написать чек лист

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#25]
- [ ] выписать список всех функций/возможностей

**Comment by Hoffasha** [comment]
https://github.com/uz0/pick.gg/wiki/%D0%A7%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F-0.00001-%D0%BF%D1%80%D0%B5%D0%B0%D0%BB%D1%8C%D1%84%D0%B0%D0%B1%D0%B5%D1%82%D0%B0%D0%BE%D0%BC%D0%B5%D0%B3%D0%B0
