### ISSUE TITLE
Обновленный дизайн

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#250]
- [x] Новый лендос
- [x] Его мобильная версия
- [x] Переработка шапки и футера всего сервиса
- [x] Новая страница со списком турниров

https://yadi.sk/i/8jCljiSCuQOTvQ
https://yadi.sk/i/JS0DEZOL6m1Eog
https://yadi.sk/i/6ZcEOc3nXvWMwA
https://yadi.sk/d/nmRky46eX3Q_Zw

**Comment by SerenityLeslie** [comment]
1. Расположение картинок с чемпионами несоответствует дизайну(моб версия).
На дизайне: 
![image](https://user-images.githubusercontent.com/54684278/68698002-a5964000-0588-11ea-9169-89c429dd5398.png) 
![image](https://user-images.githubusercontent.com/54684278/68698025-b21a9880-0588-11ea-810d-45732bf5ffb5.png)
На проде: 
![no3UW4fZWSA](https://user-images.githubusercontent.com/54684278/68698041-bba40080-0588-11ea-8c81-933f5fd21d5c.jpg)
![08YQ4Hv7eE8](https://user-images.githubusercontent.com/54684278/68698043-bc3c9700-0588-11ea-895d-18c28886b010.jpg)
