### ISSUE TITLE
Dashboard Users: не выводит юзеров в дешборде на production

### ISSUE THREAD

**Issue by Close2real** [uz0/pick.gg#255]
При открытии вкладки Users в dashboard не выводит юзеров
![image](https://user-images.githubusercontent.com/34235946/66334810-6a2da380-e942-11e9-9acc-538cddaca27b.png)

**Comment by SerenityLeslie** [comment]
Не пофикшено
![image](https://user-images.githubusercontent.com/54684278/68697559-bf835300-0587-11ea-8ec5-0ef664e8d2a7.png)

**Comment by SerenityLeslie** [comment]
Пофикшено и оттещено!
