### ISSUE TITLE
Обновление зависимостей

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#259]
- [ ] нужно посмотреть список наших зависимостей и выписать те, которые уже очень устарели (выписать сюда комментарием)
- [ ] одну за другой, обновляем зависимость и правим код
- [ ] поднимаем мультитестинг и проверяем что в целом все норм
- [ ] исправить  security vulnerabilities обьявление в корне

**Comment by ovchingus** [comment]
![image](https://user-images.githubusercontent.com/31659505/70348286-74511d00-1873-11ea-8080-89d320c9605e.png)

**Comment by ovchingus** [comment]
![image](https://user-images.githubusercontent.com/31659505/70349699-53d69200-1876-11ea-826b-ba281ca201fc.png)

**Comment by ovchingus** [comment]
![image](https://user-images.githubusercontent.com/31659505/70349775-78326e80-1876-11ea-9d6a-992df2cd0edb.png)
