### ISSUE TITLE
Фильтр на Rewards работает некорректно

### ISSUE THREAD

**Issue by SerenityLeslie** [uz0/pick.gg#269]
1. Выбрать юзера leslie the soldier
2. Выбрать во втором дропдауне is not claimed
3. Сменить на is claimed
4. Сменить обратно на is not claimed
5. В списке пусто теперь
![image](https://user-images.githubusercontent.com/54684278/68983931-48172300-0816-11ea-9b69-66780c14fbdc.png)

**Comment by SerenityLeslie** [comment]
Связанный баг: при создании реварда, с галочкой на is claimed, его вообще не видно в списке ревардов

**Comment by ovchingus** [comment]
Исправлено уже, можно закрывать?
