### ISSUE TITLE
Ошибка авторизации

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#283]
Когда заходишь с https https://pick.gg/home то получаешь при попытке авторизоваться такое:

![image](https://user-images.githubusercontent.com/8696354/69920151-6414f880-1495-11ea-8ceb-f4f5ab12b8c3.png)

**Comment by efim1382** [comment]
У меня такого не вылезало, но нагуглил что надо в google developers console добавить урл перенаправления. Я добавил

**Comment by dcversus** [comment]
@efim1382 можешь разрешить переадресации с
dev.pick.gg
ru.pick.gg
pick.gg
localhost

и в каждом случае и с http и c https

я уже дополнила правила переадресации в cloudflare на https, но на всякий
