### ISSUE TITLE
Интеграция с pubg api

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#305]
- [x] найти инфу по api
- [x] расписать что нужно чтобы подключится
- [x] в ручном режиме собрать кастомную игру и извлечь в ручную ответ сервиса (и прекрипить ответ к тикету)
- [x] написать автоматическое получение результатов
- [x] расшить интерфейс, добавить флоу к привязки с авто заполнением

**Comment by ovchingus** [comment]
Есть обертка для официального апи [npm реестр](https://www.npmjs.com/package/pubg.js), она изичная, для подключения нужен ключ апи и регион в конструктор закинуть.

Вот ссылка на официальное апи [например матчи](https://documentation.pubg.com/en/matches-endpoint.html#/matches)

Вот пример запроса и ответа 
![image](https://user-images.githubusercontent.com/31659505/70802952-ecfc3000-1dc3-11ea-8dc4-22c62b1f0c3e.png)
