### ISSUE TITLE
Возможность получить список моих турниров

### ISSUE THREAD

**Issue by danilstoyanov** [uz0/pick.gg#33]
Бекенд:
- [x] Доработка модели турнира или юзера
- [x] Создание ендпоинта для получения списка турниров, в которых юзер принимал участие

Фронтенд:
- [x] Страница "Мои турниры"
- [x] Таблица со списком турниров, в которых юзер принимает / принимал участие

**Comment by efim1382** [comment]
GET http://localhost:3001/api/tournaments/my - завершенные турниры, где выбранный юзер когда либо принимал участие
