### ISSUE TITLE
Исправить модалку для авторизации

### ISSUE THREAD

**Issue by danilstoyanov** [uz0/pick.gg#339]
**ТАСКА ЧРЕЗВЫЧАЙНОЙ ВАЖНОСТИ!**

Если пользователь ещё не зарегистрирован в системе, но хочет принять участие как аппликант или зритель, то он должен увидеть модальное окно, которое попросить заполнить ник в ЛоЛ или Пабг, ссылку на социальные сети.

Эта модалка уже существует, просто нужно проверить весь пользовательский сценарий с ней, и убедиться, что модалка отправляет корректные данные и на бекенде ничего не ломается.

**Comment by dcversus** [comment]
сейчас когда новый пользователь жмет join его просто приглашает( игнорируя заполнен ли у него профиль или нет

ЕСЛИ У ПОЛЬЗОВАТЕЛЯ НЕ ЗАПОЛНЕН ник в игре, он НЕ может подавать заявку на участие в игре
