### ISSUE TITLE
ПРАВКИ ВЁРСТКИ

### ISSUE THREAD

**Issue by danilstoyanov** [uz0/pick.gg#343]
На мобильных девайсах есть проблемы с вёрсткой. Нужно устранить.
**P.S. Сори за гигантские размеры скринов.**

![photo_2019-12-30_12-43-29](https://user-images.githubusercontent.com/18240896/71576547-0b6f6480-2b02-11ea-9cba-d0910636fa65.jpg)
![photo_2019-12-30_12-43-23](https://user-images.githubusercontent.com/18240896/71576548-0c07fb00-2b02-11ea-8126-9d0ef5c5d263.jpg)
![photo_2019-12-30_12-43-20](https://user-images.githubusercontent.com/18240896/71576549-0c07fb00-2b02-11ea-883c-506a3788366f.jpg)
![photo_2019-12-30_12-43-19](https://user-images.githubusercontent.com/18240896/71576550-0c07fb00-2b02-11ea-83d6-20dac6fc3590.jpg)
![photo_2019-12-30_12-43-17](https://user-images.githubusercontent.com/18240896/71576551-0c07fb00-2b02-11ea-894b-c5a845c3003d.jpg)
![photo_2019-12-30_12-43-15](https://user-images.githubusercontent.com/18240896/71576553-0ca09180-2b02-11ea-8539-86fed9e6a9c7.jpg)

**Comment by dcversus** [comment]
там еще кнопки join tournament пиздец как криво размещены (без отступов)
