### ISSUE TITLE
Доработка селекта выбора турнира

### ISSUE THREAD

**Issue by danilstoyanov** [uz0/pick.gg#47]
![image](https://user-images.githubusercontent.com/18240896/53518869-03f6bd80-3ae3-11e9-84d9-9a8a85b85a75.png)

- [x] добавить отображение даты в Select
- [x] сортировка даты турниров начиная с завтрашнего дня

**Comment by kot91ivan** [comment]
- [ ] добавить отображение даты в селект
- [ ] сортировка даты турниров начиная с завтрашнего дня
