### ISSUE TITLE
Принять участие в турнире

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#5]
- [x] кликая на плюсик в карточке, открывается список игроков, с возможностью выбора 
- [x] ендпоинт /tournaments/:id/setup
- [ ] Получить игроков, с которыми юзер зарегался на турнир 
![image](https://user-images.githubusercontent.com/8696354/51461575-861af600-1d6f-11e9-823c-97e6983766d5.png)

**Comment by danilstoyanov** [comment]
На данный момент можно принять участие в турнире.
Однако нужно также каким-то образом иметь возможность получить список выбранных игроков для турнира, если мы зарегистрировались на него. Сейчас, единственное что мы можем сделать - это просто вывести уведомление о том, что вы уже зареганы на данный турнир.

![image](https://user-images.githubusercontent.com/18240896/52339051-136f7300-2a1d-11e9-85ce-b4c8559737f7.png)
