### ISSUE TITLE
очередное остроумное название таски-мусорки

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#55]
- [x] фильтр по настоящему турниру
- [x] информация о самом турнире и условия (с ссылкой на правила)
- кто создатель (кликабельно)
- название настоящего турнира
- правила которые установил пользователь
- [x] расширенный статус (выбери игроков, жди матчей, следи за результатами)
- [x] под карточкой выбранного киберспорстмена показывать его личный вклад по балам (аналогично как в матчах)
- [x] авторизация через facebook / google
- [x] С САМЫМ НИЗКИМ ПРИОРИТЕТОМ i18n
- [x] создала турнир, сразу открывается модалка с выбором киберспортсменов
- [x] добавить в попап выбора игроков

# то чего не хватает
- выбрать основной сценарий кастомки/модерируемо
- загнать реальной даты
- может сменить игру?
- понятные истории/очевиднее прописать детали? обучение? подсказки? текст?
- правила и лендос, сделать черновики/к пункту выше
- обновления и уведомления в реальном времени

**Comment by danilstoyanov** [comment]
![image](https://user-images.githubusercontent.com/18240896/54083387-942ed100-4333-11e9-8410-6afc8e0a6805.png)
Добавить скролл для выбора игроков

**Comment by dcversus** [comment]
- [ ] Сразу после регистрации авторизуем и открываем страницу со списком турниров!
- [ ] Список турниров, если нет турнира - показывать плашку с отсутствием турниров
- [ ] прошедшие матчи, поправить оформление
- [ ] максимальная ширина 1024
- [ ] в списке транзакции, кликабельна ссылка на турнир
- [ ] на главной не должно быть матчей которые завершены или которые в процессе
- [ ] правила НЕ ОБЯЗАТЕЛЬНЫ для заполнения
- [ ] в правила я хочу ввести 0
- [ ] Если турнир бесплатный, то подсказка для принятия решения спрашивает просто "вы хотите с таким составом стартовать?"
- [ ] Если я создатель турнира, то принятие в нем участие С МЕНЯ НЕ БЕРЕТ ДЕНЕГ
- [ ] если только 1 человек участвует, все также видим заглушку, что людей нету
- [ ] клик по матчам, ОТКРЫВАЕТ В новом окне, если ссылки нету, то не кликабельно
- [ ] оформление страницы турнира, бьем на колонки/даем расширенную информацию/КОГДА НЕ ВЫБРАНЫ ЧЕМПИОНЫ, ТО ПЛЮСИК ОДИН И ОН ОРАНЖЕВЫЙ! (а статус говорит - выбери своего чемпиона, ждем только тебя)
- [ ] 
![image](https://user-images.githubusercontent.com/8696354/54279178-72d51b80-45a5-11e9-9d46-f1b671f9b51d.png)

**Comment by dcversus** [comment]
# Админский интерфейс
нужен простой интерфейс, чтобы добавлять/редактировать/изменять, это ПРОСТЫЕ текстовые поля ввода, редактирование и создание в модальном окне
- [ ] турниры (админка)
- [ ] фентези турниры (админка)
- [ ] матчи (админка)
- [ ] чемпионы (админка)
- [ ] результаты (админка)
- [ ] список ПОЛЬЗОВАТЕЛЕЙ (админка)
- [ ] у всех сущностей есть ДАТА КОГДА СИНХРОНИЗИРОВАНА, если создано вручную - null
- [ ] дата и время последней синхронизации (а также количество обновленной информации)
- [ ] дата и время финализации (а также сколько турниров было завершено)
- [ ] user.isAdmin + middleware

**Comment by danilstoyanov** [comment]
Что уже можно делать в админке:

Реальные турниры
- Создать турнир
- Добавить игроков (киберспортсменов) в турнир
- Удалить игрока (киберспортсмена) из турнира (при удалении игрока удаляются также его результаты из матчей)
- Добавить матч в турнир (результаты матча по умолчанию генерируются для игроков турнира)
- Удалить матч из турнира
- Удалить турнир (вместе с турниром удаляются его матчи и результаты матчей)

Правила
- Добавить новое правило
- Отредактировать имя правила
- Удалить правило

Киберспортсмены
- Добавить нового киберспортсмена
- Отредактировать киберспортсмена (имя, фото)
- Удалить киберспортсмена

Юзеры
- Изменить юзернейм
- Изменить баланс
- Предоставить / забрать полномочия админа

Что осталось допилить:

Фентези турниры
- Добавление фентези турнира из админки
- Редактирование фентези турнира (изменение коэфф., суммы входа, создателя)
- Удаление фентези турнира

ДАТУ СИНХРОНИЗАЦИИ!
ПОДРУЖИТЬ АДМИНКУ С ДАННЫМИ ИЗВНЕ!
