### ISSUE TITLE
Сайты для даты

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#69]
https://www.gosugamers.net/lol/matches - не заметил тут статы, но тут есть турниры=

https://gol.gg/tournament/list/region-ALL/ - огромная база старых турниров с очень подробной статой

https://www.leagueofgraphs.com/ - тоже много статы

https://rift.gg/en/ - софтина со статой, но внизу есть графы:  
I am a coach or a video analyst
I am a content creator or a commentator
возможно у них есть дата

https://eu.lolesports.com/en/league/rift-rivals по офф турнирам

**Comment by Hoffasha** [comment]
https://fantasy.na.lolesports.com/en-US/stats 

https://www.esportsearnings.com/

https://www.thescoreesports.com/lol/scores вот тут прямо много статы

**Comment by dcversus** [comment]
прям по полочкам, и матчи, и участники и личный счет итп
https://www.cybersport.ru/base/tournaments/2019-lck-spring-split/stage/10003668

**Comment by dcversus** [comment]
используем https://www.thescoreesports.com/lol/scores 
также исследуем еще источники - больше лучше
