### ISSUE TITLE
финализация

### ISSUE THREAD

**Issue by dcversus** [uz0/pick.gg#72]
# админка
- [x] в админке я вижу синхронизированы ли данные автоматом или созданы в ручную (type: auto/manual) (и когда было обновление)
- [ ] ЭТА ГАЛОЧКА ПОД ВОПРОСОМ! в админке хочу видеть список завершенных фентези турниров, имена победителей и сколько кому денег отсыпало (глобальный журнал транзакций?) 

# турниры
- [x] кнопки зачислить деньги и снять - disabled
- [x] баланс нового участника - 5000 по умолчанию
- [x] переключение локализации через url
- [x] в настройки добавить смену локализации ( И ПРОВЕРИТЬ РУССКУЮ ЛОКУ!)
- [x] когда очков нету - стили разьебаны
- [x] кнопки нет/отмена итп, НЕЙТРАЛЬНОГО ЦВЕТА (темный фон и белый текст)
- [x] Я НЕ МОГУ ВСТУПИТЬ В ТУРНИР, КОТОРЫЙ НАЧАЛСЯ!!
- [x] финализацию можно вызвать по кнопке из админки
- [x] доделать финализацию с интеграцией даты (учитывать асисты/смерти/убийства)
- [x] страница со списком фентези турниров, мы видим только фентези турниры из будущего (начиная с завтрашнего дня) - выставлен фильтр по умолчанию с датой

# авторизация и профиль
- [x] участвует в турнирах, страница публичного профиля (кажется что ничего не работает, не вижу истории турниров)
- [x] кнопка войти на главной - авторизация/регистрация через гугл
- [x] добавить иконку Google рядом c текстом войти
- [x] скрыть кнопки/ссылки на обычную авторизацию/регистрацию
- [x] страница профиля пользователя, добавить email (gmail) который нельзя сменить/отвязать
- [x] заполнять автоматом имя (username) из данных гугла
- [x] заполняем аватарку из гуглового профиля
- [x] позволить редактировать username (проверить что вся система не наебнется, от того что мы изменили username)

# обновление в реальном времени
- [x] список турниров
- [x] список фентези турниров
- [x] историю транзакций и баланс
- [ ] публичный профиль
- [ ] рейтинг
- [ ] СТРАНИЦУ ТУРНИРА!
- [x] когда обновляется фентези турнир в котором я принимаю участие - видеть notification, клик на который открывает фентези турнир

**Comment by danilstoyanov** [comment]
Запилить обновление баланса после того как турнир был создан
