### ISSUE TITLE
Регистр

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#73]
- залогинился под "hoffa"
- зашел в настройки
- поменял логин на Hoffa
- логаут
- попытка залогиниться под Hoffa
- ошибка - юзер не найден
- сразу же логинюсь как hoffa та же ситуация, спасла авторизация через гугл
- зайдя через гугл поменяв ник на старый (hoffa) 
- все стало норм

**Comment by danilstoyanov** [comment]
Баг неактуален, т.к. сейчас действует только регистрация и авторизация строго через Google
