### ISSUE TITLE
Кириллица 

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#74]
Предлагаю запретить возможность делать ник на русском языке, подкрепив сообщением wrong symbols, так как приложение дает возможность это сделать, но по итогу юзер не найден. Я так запорол 1 акк 
Тоже и с настройками юзера, при смене ника на русский, все ломается

**Comment by danilstoyanov** [comment]
Неактуально в связи с переходом на гугл аторизацию / регистрацию
