### ISSUE TITLE
Рега через гугл

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#76]
* зашел на http://pick.gg/ (1 скрин)
![image](https://user-images.githubusercontent.com/46968947/55306295-69302c80-545c-11e9-8dc4-780728647525.png)
* выбираю мыло которое не регал (shmidtadnrea@gmail.com)
![image](https://user-images.githubusercontent.com/46968947/55306311-7c42fc80-545c-11e9-952c-fc089e784bb7.png)
* следующее окошко 
![image](https://user-images.githubusercontent.com/46968947/55306487-2753b600-545d-11e9-9e7d-2b759894218a.png)

Ожидаемый результат - я должен придумать пароль и сразу пользоваться сервисом 
Фактический - мне нужно писать мыло заново, можно даже не гугловское - получился такой акк. После лога на этот акк уже не зайти  и нужно создавать заново с гугловским мылом.
![image](https://user-images.githubusercontent.com/46968947/55306446-f1163680-545c-11e9-8743-290942fce93c.png)

**Comment by danilstoyanov** [comment]
Выпилены роуты /login и /register. Оставлена возможность логиниться/регаться только через гугл.
