### ISSUE TITLE
Реал тайм

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#80]
## На данный момент пишу, что не обновляется в реал тайме, помогает только f5

- [x] при создании турнира деньги списываются только после f5

- [x] аватарка обновляется не в реал тайме

- [x] после обновления ника в настройках пользователя также требуется f5 

- [x] после смены локализации в шапке не переводится rating, опять же до f5

**Comment by danilstoyanov** [comment]
Залил апдейты, можно проверять
