### ISSUE TITLE
Создание матча в админке для турнира

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#82]
- захожу в админку
- создаю реальный турнир
- добавляю игроков
- жму кнопку создать матч
- в окошке создания матча хочу его переименовать (match name)
- ввожу другое имя, жму update

Ожидаемый результат - у меня поменялось название
Фактический результат - у всех матчей название New match которое не обновляется
![image](https://user-images.githubusercontent.com/46968947/55551008-6d6d7b80-56e2-11e9-97ca-994aab037d40.png)

**Comment by danilstoyanov** [comment]
Доработал обновление, можно проверять
