### ISSUE TITLE
Имя фентези турнира в всплывашке

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#83]
- создал фентези турнир
Ожидаемый результат - в окошке будет корректное название
Фактический результат на картинке :(
![image](https://user-images.githubusercontent.com/46968947/55551346-41062f00-56e3-11e9-8ce6-2f9ea22ca8d1.png)

**Comment by danilstoyanov** [comment]
Выкатил быстрофиксы, нужен повторный тест
