### ISSUE TITLE
Создание турнира модалка

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#85]
Создаю турнир
Появляется окошко: Do you really want to create a tournament?
Нажимаю Yes, оно не закрывается, турнир создается.

![image](https://user-images.githubusercontent.com/46968947/55626238-a0337480-57b3-11e9-8351-578244eb0aa1.png)

**Comment by danilstoyanov** [comment]
Окошко теперь закрывается, турнир создаётся

**Comment by danilstoyanov** [comment]
@Hoffasha запилил апдейт, нужен повторный тест
