### ISSUE TITLE
Кнопка Join tournament

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#86]
Предлагаю сделать ее покрупнее и возможно другим цветом (зеленым?)
Многие рандомные ребята, которых опрашивал, терялись и у них горело желание нажать на кнопку Match 1, match 2, new match. Или же с позицией кнопки подумать. Вверху справа не сразу кидается в глаза
![image](https://user-images.githubusercontent.com/46968947/55627804-ba6f5180-57b7-11e9-863f-e37f549053cf.png)

**Comment by dcversus** [comment]
Кнопку и правда бы заметнее, может не сделать размером с карточку игрока и с иконкой плюсик. Цвет однозначно акцентный, никаких зелёных или ещё левых цветов

**Comment by dcversus** [comment]
Менять местами итп не стоит, так совсем потеряемся
