### ISSUE TITLE
Сделать статичную шапку

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#87]
После создания турнира многие хотят выйти на главную, со всеми турнирами, возможно ли какую нибудь стрелочку сделать, или статичную шапку, чтобы вниз не уходила,  где также нажав пик.гг можно на главную попасть.

**Comment by dcversus** [comment]
Статичную шапку? По шапке бы за такую терминологию

Вверху бы кнопку фентези турниры, которая бы вела на ‘главную’. Стрелочка назад хз, для мобилы мб, но такое

Закреплять шапку в верхней части экрана - не надо, отвратительно
