### ISSUE TITLE
AKD->KDA

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#92]
Пожалуйста, сделайте тут Kills Deaths Assists, я крышей поехал, пока заполнял таблицу сверяя скоры с матча в лоле :(
![image](https://user-images.githubusercontent.com/46968947/55809081-f96e1180-5aed-11e9-872d-72ae355f984e.png)

**Comment by danilstoyanov** [comment]
Дофиксил этот отвратительный баг)
Можно проверять
