### ISSUE TITLE
Футер 

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#93]
Предлагаю добавить блок в нижней части страницы, куда выносят полезную, но не первостепенную информацию, которая также будет отделять игроков, которые участвуют в фентези турнирах.
![image](https://user-images.githubusercontent.com/46968947/55809423-90d36480-5aee-11e9-8b46-b0248f7753c9.png)

**Comment by dcversus** [comment]
Ну футер с одной строчкой 
2019 (с) uz0 | terms and agreement
