### ISSUE TITLE
Сделать поиск пользователей

### ISSUE THREAD

**Issue by Hoffasha** [uz0/pick.gg#96]
Вот напрашивается эта кнопка, чтобы быстро по нику найти пользователя
![image](https://user-images.githubusercontent.com/46968947/55810574-78644980-5af0-11e9-9a29-ed0ee17eed25.png)

**Comment by dcversus** [comment]
Нет не напрашивается, пользователи вторичны - фентези турниры первичны. Чисто по приоритетам
